USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON PNLCOACHS
REBUILD;
ALTER INDEX ALL ON PNLREFEREES
REBUILD;
ALTER INDEX ALL ON PNLSTADIUMS
REBUILD;
ALTER INDEX ALL ON PNLGOALS
REBUILD;
ALTER INDEX ALL ON PNLPLAYERS
REBUILD;
ALTER INDEX ALL ON PNLTEAM
REBUILD;
ALTER INDEX ALL ON PNLAWAYTEAM
REBUILD;
ALTER INDEX ALL ON PNLMATCHES
REBUILD;
GO